# Copyright (c) 2026 Pointmatic
# SPDX-License-Identifier: Apache-2.0
"""Cross-link integrity for ModelFoundry's first-party spec docs (Story F.b).

Every relative markdown link in the project's own `docs/specs/*.md` must resolve
to a file that exists on disk, so the spec set stays internally navigable and a
release reader never hits a 404. The checker validates *file existence* of
relative links (the unambiguous, high-value failure mode); anchor-fragment
slugs are out of scope here and are swept by hand.

Vendored dependency-spec copies under `docs/specs/datarefinery/` and
`docs/specs/nbfoundry/` are excluded: their relative links are authored against
those sibling projects' own repository layouts and are correct *there*. Rewriting
them to resolve locally would corrupt the vendored copies and they would re-break
on the next vendor refresh.

Links *into* `docs/project-guide/` are likewise skipped: that tree is
tool-generated install output (regenerated by `project-guide init`),
intentionally uncommitted, so it is present in a working dev tree but absent in a
clean checkout / CI. Checking its existence would make the suite pass or fail on
local install state rather than on the first-party docs (Story G.c).

Snapshots under `docs/specs/.archive/` are excluded too: `archive_stories` moves
completed-phase story text there *verbatim*, so its relative links — authored
against the original `docs/specs/` location — resolve one directory level too
shallow from `.archive/`. The snapshot is frozen history, not a live navigable
doc, so its links are intentionally not rewritten or checked (Story H.e).
"""

from __future__ import annotations

import re
from pathlib import Path

# Repo root is three levels up from this file: tests/unit/<file>.
REPO_ROOT = Path(__file__).resolve().parents[2]
SPECS_DIR = REPO_ROOT / "docs" / "specs"

# Vendored sibling-project specs — see module docstring.
VENDORED_SUBDIRS = ("datarefinery", "nbfoundry")

# Frozen archived story snapshots (archive_stories output) — see module docstring.
ARCHIVE_SUBDIR = ".archive"

# Tool-generated install output, intentionally uncommitted — see module docstring.
INSTALL_OUTPUT_DIR = (REPO_ROOT / "docs" / "project-guide").resolve()

_LINK_RE = re.compile(r"\[(?P<label>[^\]]+)\]\((?P<target>[^)]+)\)")


def _first_party_specs() -> list[Path]:
    """First-party `docs/specs/*.md`, excluding vendored sibling-project copies."""
    out: list[Path] = []
    for md in sorted(SPECS_DIR.rglob("*.md")):
        rel = md.relative_to(SPECS_DIR)
        if rel.parts and (rel.parts[0] in VENDORED_SUBDIRS or rel.parts[0] == ARCHIVE_SUBDIR):
            continue
        out.append(md)
    return out


def _broken_relative_links(md: Path) -> list[tuple[str, str]]:
    """Return `(label, target)` for each relative link in `md` whose file is missing."""
    broken: list[tuple[str, str]] = []
    for m in _LINK_RE.finditer(md.read_text(encoding="utf-8")):
        target = m.group("target")
        # External, anchor-only, and mailto links carry no local file to check.
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        path_part = target.split("#", 1)[0]
        if not path_part:
            continue
        resolved = (md.parent / path_part).resolve()
        # Skip tool-generated install output (e.g. project-guide/go.md): present
        # after `project-guide init`, absent in a clean checkout — not first-party.
        if resolved == INSTALL_OUTPUT_DIR or INSTALL_OUTPUT_DIR in resolved.parents:
            continue
        if not resolved.exists():
            broken.append((m.group("label"), target))
    return broken


def test_first_party_specs_exist() -> None:
    """Guard against the glob silently matching nothing (e.g. a moved docs tree)."""
    specs = _first_party_specs()
    assert specs, f"no first-party spec docs found under {SPECS_DIR}"


def test_no_broken_relative_links_in_first_party_specs() -> None:
    """No relative markdown link in a first-party spec doc points at a missing file."""
    failures: dict[str, list[tuple[str, str]]] = {}
    for md in _first_party_specs():
        broken = _broken_relative_links(md)
        if broken:
            failures[str(md.relative_to(REPO_ROOT))] = broken
    assert not failures, "broken relative cross-links:\n" + "\n".join(
        f"  {doc}: [{label}]({target})"
        for doc, links in failures.items()
        for label, target in links
    )
